# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'show keyvault secret'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'DevOps-Keyvault-Connect'
    KeyVaultName: 'formula11kv'
    SecretsFilter: 'formula1dlaccountkey'
    RunAsPreJob: false
